name: bearbox
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^8.0.3
  dartz: ^0.10.1
  go_router: ^14.8.1
  file_picker: ^9.2.1
  flutter_bloc: ^9.1.0
  firebase_auth: ^5.5.1
  dotted_border: ^2.1.0
  firebase_core: ^3.12.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  dropdown_button2: ^2.3.9
  sliding_up_panel: ^2.0.0+1
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.3.3
  shared_preferences: ^2.5.2
  easy_localization: ^3.0.7+1
  image_picker_for_web: ^3.0.6
  image_picker_loading_jm: ^0.0.10
  video_player: ^2.9.3
  video_player_web: ^2.3.4
  flutter_carousel_widget: ^2.2.0

  my_fit_ui_kit:
    git:
      url: https://github.com/JEISONVARGAS1/bearbox_ui_kit.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
